vich_uploader:
  db_driver: orm

  mappings:
    users:
      uri_prefix: /img/users
      upload_destination: '%kernel.project_dir%/public/img/users'
    file:
      uri_prefix: /files
      upload_destination: '%kernel.project_dir%/public/files'
